{
  retirements(
    orderBy: eventId,
    where: {
      eventId_gte: {{ skip_num }},
      eventId_lt: {{ skip_num + 100 }}
    }
  ) {
    id
    creationTx
    amount
    timestamp
    token {
      address
    }
    creator {
      id
    }
    eventId
    certificate {
      id
    }
  }
}
